# Generated by Django 5.1.5 on 2025-01-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants_photos/')),
                ('date_de_naissance', models.DateField(verbose_name='Date de Naissance')),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du Père')),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la Mère')),
                ('parent_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact des parents')),
                ('address', models.TextField()),
                ('boursier', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=3, verbose_name='Boursier')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name="Date d'Entrée")),
                ('idclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Ecolage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=[('janvier', 'Janvier'), ('février', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('août', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('décembre', 'Décembre')], max_length=10, verbose_name='Mois')),
                ('payé', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3, verbose_name='Payé')),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Boursier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madressat', models.CharField(max_length=200, verbose_name='Nom de Madressat')),
                ('cheick', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheick Responsable')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact de Madressat')),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boursier', to='main.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('raison', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Décision')),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annees', models.IntegerField(default='2025', verbose_name='Année')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5')], default='semester 1', verbose_name='Semestre')),
                ('moyen', models.FloatField(verbose_name='Moyenne')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='notes/', verbose_name='Fichier')),
                ('type', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=10, verbose_name='Type')),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('presence', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=7, verbose_name='Présence')),
                ('idclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classmodel', verbose_name='Classe')),
                ('identifiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etudiant')),
            ],
        ),
    ]
