# Generated by Django 5.1.5 on 2025-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classmodel_options_etudiant_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='nom',
            field=models.CharField(choices=[('MS', 'Moyenne Section'), ('GS', 'Grande Section'), ('CP', 'Cours préparatoire'), ('CE1', 'Cours élémentaire 1'), ('CE2', 'Cours élémentaire 2'), ('CM1', 'Cours moyen 1'), ('CM2', 'Cours moyen 2'), ('6', 'Sixième'), ('5', 'Cinquième'), ('4', 'Quatrième'), ('3', 'Troisième'), ('2nd', 'Seconde'), ('1er', 'Première'), ('Tle', 'Terminale')], max_length=100, verbose_name='Nom de la classe'),
        ),
    ]
