# Generated by Django 5.1.5 on 2025-01-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_classmodel_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='idclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classmodel', verbose_name='Classe Etudiants'),
        ),
    ]
