# Generated by Django 5.1.5 on 2025-01-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_etudiant_idclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='idclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classmodel', verbose_name='Classe Etudiants'),
        ),
    ]
