# Generated by Django 5.1.5 on 2025-01-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_etudiant_idclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'Etudiants"),
        ),
    ]
