# Generated by Django 5.1.5 on 2025-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='etudiants_photos/', verbose_name="Photo de l'Etudiants"),
        ),
    ]
