# Generated by Django 5.1.5 on 2025-01-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_etudiant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiduTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('professeur', models.CharField(blank=True, max_length=100, null=True)),
                ('commence', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('jours', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('idclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classmodel', verbose_name='Classe Etudiants')),
            ],
        ),
    ]
