# Generated by Django 5.1.5 on 2025-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emploidutemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidutemp',
            name='room',
        ),
        migrations.AlterField(
            model_name='emploidutemp',
            name='jours',
            field=models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi'), ('Sunday', 'Dimanche')], max_length=10),
        ),
    ]
