# Generated by Django 5.1.5 on 2025-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_emploidutemp_room_alter_emploidutemp_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
