# Generated by Django 5.1.5 on 2025-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_presence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='temp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
