# Generated by Django 5.1.5 on 2025-01-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_presence_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='temp',
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
