# Generated by Django 5.1.5 on 2025-01-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_professeur_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='professeures_photos/', verbose_name="Photo de l'Professeurs"),
        ),
    ]
