# Generated by Django 5.1.5 on 2025-01-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
