# Generated by Django 5.1.3 on 2025-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_classmodel_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('date_d_embauche', models.DateField(verbose_name="Date d'embauche")),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
    ]
