# Generated by Django 5.1.3 on 2025-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='personnel_photos/', verbose_name='Photo des Personnels'),
        ),
    ]
