# Generated by Django 5.1.2 on 2025-01-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_personnel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boursier',
            name='identifiant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='idboursier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.boursier', verbose_name='Boursier Etudiants'),
        ),
    ]
