# Generated by Django 5.1.5 on 2025-05-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_boursier_identifiant_etudiant_idboursier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='idclass',
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classmodel', verbose_name='Classe Etudiants'),
        ),
        migrations.AlterField(
            model_name='note',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (0, 'Annuelle')], default='semester 1', verbose_name='Semestre'),
        ),
    ]
