# Generated by Django 5.1.5 on 2025-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_professeur_idclass_matiere_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='personnel_photos/', verbose_name='Photo de Personnel'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='professeures_photos/', verbose_name='Photo du Professeur'),
        ),
    ]
