# Generated by Django 5.1.5 on 2025-05-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_personnel_photo_alter_professeur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='main.professeur', verbose_name='Professeur'),
        ),
    ]
